# By default, the root cardinal directory is the location of this config file. The root
# directory can be changed by uncommenting this line:
# root_dir="/path/to/cardinal/"

[docker_env]
# Cardinal flags
CARDINAL_NAMESPACE="my-world-1"

# EVM Flags
# this value must come from the celestia client. https://docs.celestia.org/developers/node-tutorial#auth-token
DA_AUTH_TOKEN=""
DA_BASE_URL="http://celestia-devnet:26658"
DA_NAMESPACE_ID="67480c4a88c4d12935d4"
CHAIN_ID="world-engine"
 # this is a test mnemonic and should not be used in production. 
KEY_MNEMONIC="enact adjust liberty squirrel bulk ticket invest tissue antique window thank slam unknown fury script among bread social switch glide wool clog flag enroll"
FAUCET_ADDR="world142fg37yzx04cslgeflezzh83wa4xlmjpms0sg5"
BLOCK_TIME=-1
