[cardinal]
CARDINAL_NAMESPACE = "defaultnamespace"     # A namespace must be a unique alphanumeric string
CARDINAL_ROLLUP_ENABLED = "false"           # Enables rollup mode
CARDINAL_LOG_LEVEL = "info"                 # Must be one of (debug, info, warn, error, fatal, panic, disabled, trace)
CARDINAL_LOG_PRETTY= "true"
REDIS_ADDRESS = "localhost:6379"                   # UNIX Domain Socket or TCP Address
REDIS_PASSWORD = "very_unsafe_password_replace_me" # If TCP address is used, setting a password is encouraged in production
TELEMETRY_TRACE_ENABLED = false                    # Enables OpenTelemetry tracing
TELEMETRY_PROFILER_ENABLED = false                 # Enables Datadog profiler
BASE_SHARD_SEQUENCER_ADDRESS = "localhost:9601"    # Required if rollup mode is enabled
BASE_SHARD_ROUTER_KEY = "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ01" # Secure auth token for game shard

[evm]
# DA_AUTH_TOKEN is obtained from celestia client and passed in from world.toml. 
# See https://docs.celestia.org/developers/node-tutorial#auth-token
DA_BASE_URL="http://celestia-devnet"
DA_AUTH_TOKEN=""
DA_NAMESPACE_ID="67480c4a88c4d12935d4"
CHAIN_ID="world-420"
# CHAIN_KEY_MNEMONIC is a test mnemonic and should not be used in production. 
CHAIN_KEY_MNEMONIC="enact adjust liberty squirrel bulk ticket invest tissue antique window thank slam unknown fury script among bread social switch glide wool clog flag enroll"
FAUCET_ENABLED = false
FAUCET_ADDRESS = "aa9288F88233Eb887d194fF2215Cf1776a6FEE41" # ETH address without leading 0x (Default: account 0 of CHAIN_KEY_MNEMONIC)
FAUCET_AMOUNT = "0x56BC75E2D6310000" # ETH in wei unit, encoded as hexadecimal (Default: 100 ETH)

[nakama]
ENABLE_ALLOWLIST="false" # enable nakama's beta key feature. you can generate and claim beta keys by setting this to true
# The number of undelivered notifications Nakama will allow before shutting down a connectino to a client.
# See https://heroiclabs.com/docs/nakama/getting-started/configuration/#socket.outgoing_queue_size 
OUTGOING_QUEUE_SIZE=64
# Enables tracing within Nakama, which integrates with external tracing tools such as Jaeger for visualizing system performance.
NAKAMA_TRACE_ENABLED = true   
# Enables metrics collection within Nakama, integrating with Prometheus for system metrics tracking.
NAKAMA_METRICS_ENABLED = true
# Trace sample rate. valid values are between 0.0 to 1.0 inclusive. This is a float value.
NAKAMA_TRACE_SAMPLE_RATE = 0.6
# Prometheus scraping interval in seconds.
NAKAMA_METRICS_INTERVAL = 30

[common]
# A key used by both Cardinal and EVM to coordinate activities
ROUTER_KEY = "router_key"