## Merge with docker-compose.yml in the root directory.

## Override Docker Cardinal services build target for debugging purposes
## and add container capabilities (cap_add) and security_opt
services:
  cardinal:
    build:
      target: runtime-debug
    cap_add:
      - SYS_PTRACE
    security_opt:
      - "seccomp:unconfined"
