name: Test

on:
  pull_request:
  push:
    branches:
      - main

env:
  GO_VERSION: 1.22.1

jobs:
  unit-test:
    name: Unit Tests
    runs-on: namespace-profile-linux-4vcpu-8gb-cached
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          ## skip cache, use Namespace volume cache
          cache: false
      - name: Setup Namespace cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: go
      - name: Run Unit Test
        run: |
          cd cardinal
          make test
